const AUTH_USER = 'AUTH_USER';
const ERROR_AUTH = 'ERROR_AUTH';

const FETCH_SUCCESS = 'FETCH_SUCCESS';
const FETCH_ERROR = 'FETCH_ERROR';

const RESET_DATA = 'RESET_DATA';

export { AUTH_USER, ERROR_AUTH, FETCH_SUCCESS, FETCH_ERROR, RESET_DATA }